### PR TITLE
Fix: mapbox api call for long routes

### LINKED ISSUE #94: [Bug]: HttpException: HttpException: Invalid statusCode: 413, uri = https://api.mapbox.com/styles/v1/mapbox/dark-v11/static/path-12+fff-0.8(oxgq%40gkvpHd%40IeAPJFC%40DBC%40NHRC_%40KJADDEADIGCKBJ%3FOCNBICLH%3FCAFHBQIOCOH%3FId%40MBN%40MQFG%3FPIAF_%40LEPz%40v%40%5DT%5EAvBk%40ZM...
Sentry Issue: [SENSEBOX-BIKE-FLUTTER-9F](https://reedu-0b.sentry.io/issues/6575933055/?referrer=github_integration)

```
HttpException: HttpException: Invalid statusCode: 413, uri = https://api.mapbox.com/styles/v1/mapbox/dark-v11/static/path-12+fff-0.8(oxgq%40gkvpHd%40IeAPJFC%40DBC%40NHRC_%40KJADDEADIGCKBJ%3FOCNBICLH%3FCAFHBQIOCOH%3FId%40MBN%40MQFG%3FPIAF_%40LEPz%40v%40%5DT%5EAvBk%40ZMI%3FcA%5Dq%40s%40VDpB%7C%40%5Ej%40Lj%40Mr%40eB~BLN%5EBj%40NjBRt%40X%7C%40TzB%60A~%40h%40%5EL%60%40JlALdAr%40%5E%60%40fAv%40%5ENIPcANeEZgGp%40NBHJEZL%40%40LVTbAd%40%40HGB%3FBCEC%3F%40%40CGGF%40ADLFBE%40KCPE%3FBWC%40CDC%3F%40AIE%3FJA%3FIB%3FMI%40DCCFDWGm%40g%40eA_%40YLMN%40Ad%40%40A%40BDXEEBEIA%40%3FC%3FB%3FAB%3FG%3F%40%3FGEH%3F%3FDY%3FAEF%3FKQJHEDKIDB%40PXOYRE%40%3FIBGFBGEJ%3Fa%40N%40%40HEG%40ACJBBGAACLDCAC%40%3FEAB%3FK%3FGDB%40F%3FBECDHAKCJB%3FCQ%3FF%40BGB%3FC%3FNBOANCP%40k%40BV%3FS%40GEd%40%3FSBSIZHFAM%40%3FC%40JCEN%3F%3FIKDB%3FA%40LCD%40IACAB%3F%5DAZFOGFBBCB%3FADGANAK%3FFCGBFEK%40G%40%3FBUB%40BP%40HGP%3FC%40B%40LAC%40BBADo%40SJDLGDKH%3FIIMEsACuCiAcEoBeKqByBbA_HfEe%40J~%40%60%40r%40b%40lAxAXv%40%60%40t%40W%5EsAXqD~%40k%40f%40n%40z%40BRk%40L_CJ_ABnAFJN%40ICD%3FEE%3FFAE%40EE%40BD%3FGCDCC%3FDFEECF%3FGFPB%3FE%3FJA%3FGGDF%40CAAB%3FEAHCCFCIBRIOL%3FEFCE%3F%40ABD%40EEHHOG%40BBMAEHAGJDOCGQJF%40FJ%3FJFCBIGG%40CLDCJDDGUGFECFI%40%3FOE%3FBGABDHE%3F%3FBTLOSFBCALGOACJCD%3FCNJ%3FI%40HHKIBF%40EE%3FHFK%40KESE%40RBW%40ACTJA%3FBBJVG%5BK%3FJAB%40MCR%3FG%3FJG%40DICD%3FFDCA%40EIBCCB%3FW%3FCB%40%3FIGSCgArAq%40Rm%40%3F%7B%40IqBEw%40Aa%40HAz%40Qb%40Gb%40BdAQz%40sCOuBCo%40DiBTe%40Vi%40%40sCQkBCqCS%7BCIq%40EWGC%7DCEWaEFuA%3FmAWsCq%40mDu%40uA_%40%40%40kAQsCu%40cDkAiCy%40yBaAcA%5B%7B%40k%40k%40m%40eBcBcAe%40q%40k%40%7D%40c%40%7D%40%5Ds%40o%40y%40%5DqFc%40%7D%40EyCScDGmABmAHiAPaATaExA_Cn%40aANcFLiAAcAEa%40HCTLND%40ABFFDLI%60%40LMd%40GOCFKAEYCKBX%3F%3FJALQFHA%3FCt%40i%40FI%40Ih%40%40AAHTDARJJ%3Fa%40WSGERb%40j%40Ew%40X%3FWDp%40Bm%40%60%40P_%40K%40%40QKT%7B%40%40QAX%3FGBRYB_AMTEZ%3FQ%40VDPEI%40e%40GX%40UCVFTAi%40%40ZE%5DXCEB%40BOG%40BEEAO%3FVG%5EFY%3FHCDAEKVD%3FLMDKAC%3FPJMGE%40IB%3FMZT%5DSh%40GFuAGEAn%40%3F%40ESDQ%3FBECAC%40%60%40k%40t%40BbE%3FrBQdB%5BtIkC~B%5BbCGzBBxBRfF%60A%7CBl%40%60Bp%40p%40%60%40%60A%7CAn%40v%40v%40t%40fAr%40bAh%40~Al%40rE%7C%40xHfBdD%7C%40hDp%40vIxAxAJzAG%7CDYzDo%40bBDvAZ~Af%40rAKDu%40C%7D%40Bg%40jAKxDFtCHfCAIsAZqBDmBCa%40j%40a%40bCgAdAi%40z%40g%40j%40Wx%40ABi%40GF%40LODCk%40%3F%40DAC%3F%3FBCAD%3FC%40%40AA%3FBBEGC%40f%40PMBLMIAC%40x%40K%60D_BbC%7DA%60UdChCrA%5EZrA%60At%40Rz%40AfBQKZw%40Pa%40ZJHHG%3FCEACEVU%3FDJJ%3FD%3FAINHIDHHEDBe%40ETGDBC%3FD%3FICCMFLKC%3FEJGN%40DJKb%40KLFNPJM%3FND%40Db%40GYB%5E%60%40D%40ICAEC%40BAE%3FD%40E%3FB%3FE%40AC%40BC%40FCC%3FB%3FECRAK%40CJNKMBF%40C%3FEJK%40GCKFD%40i%40%3FDCSHJ%40IBD%3F%3FACABCf%40IFDPIFISFEFYJQDj%40Oc%40Hd%40QVQD%3F%3FDQAP%3FKCE%40%3FCHFI%3FXKKJBAG%40F%3FGAD%3FC%40B%3FC%3FB%3FCDAEFAI%3FF%40E%3FAUa%40w%40UGS%40_%40H%5DAKC%40Ib%40QFCDBADNMJBGOAMC%3FDF%5BCFBT%40%3FBD%40RQiBEe%40%7CAW~DQzEUzCLA%3FGF%3FJp%40%3FzDABAEEP%5DhFACOPMt%40Ip%40FpCCj%40IlACCUJKtCKr%40Qp%40i%40h%40cANgAAeAAYEiDMM%40V%40ACG%3Fa%40%40DQEMKC%3FHj%40b%40%60%40J%60%40%40XFg%40aBN%40C%40BDiAD%7C%40DqEn%40WAiAOaBL_EBcAEa%40Qm%40GqOYuHk%40yFKSN%40%60BGbBIv%40%5BfBC%7C%40JrBCdBo%40RyCUgCKwFAy%40EyB%40%7BBEc%40Pa%40hEQBu%40%40cAUsBiAy%40OJ%40YHPB%5BK%3FIDAGHBAc%40EQJF%3FMEDB%40DF%3FEIH%40IDCAB%3FACR%40DBBF%40GM%40H%40AM%40D%60%40%40XFPEH%40SHlCwBpAy%40z%40e%40tB_BrEoC~EkDrE%7BCdAw%40xEyCzB_BHMC%3FFCf%40c%40bAg%40hAe%40hA_%40t%40MCDpAMxACnGJpDVrDHhGDtA%3Fj%40ECWs%40gDS%7BBMg%40%5Dq%40uAoAi%40s%40o%40k%40Qo%40Bc%40SOIAs%40RWEMq%40g%40y%40c%40o%40aAiAq%40k%40Ei%40vB%7B%40e%40i%40mCy%40eA_%40%40%40%5BOZs%40hAeA_AOOSBAD%40QSBAC%3FCBDCE%40Wf%40JM%40GAJHMP%3Ft%40NXPIRCd%40%7B%40h%40b%40d%40lD%7CAnDlBdAd%40VCfBm%40dAFtBv%40z%40%60%40d%40h%40Vf%40Np%40Xt%40Xf%40~AlAtAn%40vBR%60BIf%40KECh%40CfARRdAItAKtC_%40%60CGFCCWvAI~BSrBAz%40%3FAEf%40Mn%40SnCgAxBUz%40MpBK~%40%40z%40K%7CB%40tBKf%40KHOHEKGHGj%40e%40%7CCAx%40Jx%40Et%40K%5C%3FCKLGx%40BE%5EJRf%40f%40%7C%40Hz%40%40l%40Yp%40%5DpCYbAYjBOn%40Yp%40%7B%40zCMr%40g%40pBW%60Bc%40jBUnBaAlDs%40hBg%40r%40%7B%40t%40aAf%40aBXeBR%7D%40FFNGl%40c%40jBYdCO%60A%5Dx%40e%40hBc%40rDGx%40W%7C%40iAvHa%40%60AMdB_%40nBG~%40D~%40z%40pCt%40%7CCl%40fATfA%60B~EPnA%60%40nAXnAr%40nDf%40vA%5EpA%5E~%40Bz%40%3FfA%5D%7CC%40fAEdAFtB%40%60BYX%40TEVG%7C%40Ij%40%40%5EHJLt%40CT%5DVw%40Rw%40%3Fe%40J%5BPr%40%5D%3FAAD%40KRIf%40%40ECH%3FIDAJD%3FGGQ%3FMPQBEFGIFGC%3F%40ADBE%3FBCA%40F%3FG%40JAI%3FPEM%40ECFDIB%3FCH%40A%40%40CI%40J%40FEM%3F%40D%40%3FE%3F%40%40%40%3FACCBD%3FC%3F%40CC%40A%40%40%40G%40BDC%40PGPDDJJG%3FCGAKBB%40S%40ABBEOKLGG%3F%3F%40%3FAABBEGD%40%3FDAG%40FCG%3FFExASb%40%5DJ_B%40w%40Ay%40BaDA%7D%40Fy%40Ho%40Cs%40Fy%40Jm%40%3Fk%40Q%5BUAA%40%40BAm%40Ne%40Am%40So%40Ug%40Ig%40Ye%40%7B%40mD%7DA%7BEcAwDKi%40Si%40cAoD%5Bc%40Qm%40Mm%40SyAk%40_BOm%40Do%40Bs%40Ew%40Fw%40z%40iBLu%40Eu%40%5EeBCk%40jAmFv%40sFF%7B%40h%40qBP%5BI%3FBaAGq%40L%7D%40%5E%7D%40R%7B%40JaAPcAVcA%7CBuMf%40qDXsANuAfA%7DFCy%40OON_%40MMiCO%7BEG_%40Iy%40e%40Oe%40Ts%40Oo%40c%40g%40yAe%40WOJCD%40Vm%40%3F%40L%7BAPo%40X_EHkBRsBNy%40DmBCsB%3FeAFy%40VqBBi%40C%40FMDa%40Am%40BIFq%40Jq%40h%40qBVyFOgABUt%40GvABtAHfD%3FpCDCBQi%40WoBHCLBm%40_%40G%3FCHTINAU%3F%40Cb%40BOAH%3F%40BDCG%3FKHB%3FE%40BEOCHBGA%40CJ%40KDS%40%40BN%40NGP%3F%3FJE%40HHCKBc%40_%40q%40a%40wA%7BA%7BC%7DAuA%5Ba%40AOKW_%40OaABUKEg%40Ia%40EIcAZuAFF%3FJLGFDC%5BJAGC%3FH%40EABQURDEb%40BCGS%3FGCNGC%40%40DE%40NFHHHGIDECF%40EA%3FGJONCe%40%40UJKZqAv%40qAE%7D%40Is%40AW%40c%40Rg%40Ac%40DD%7CAFz%40StAMVgAKkAGcCS%7D%40B%7D%40Vo%40Ty%40Js%40Gi%40%3FyBI%7BBUuBM_AAy%40F_A%3FQQEuCIi%40_%40OaAHyAD%7DAC%7DN%7DCsA%5DoEaAkA_%40qAYoA%5DaFkA%7D%40_%40m%40k%40u%40k%40_Ak%40q%40o%40i%40u%40sCqB%7B%40Y_AMsBe%40wEm%40gDGyCJgANiAVaAZ%7D%40%60%40yBp%40aARcANqAJwCHoAAcAEIl%40ECEH%3F%5CIZp%40GBSa%40Ja%40RCA~%40WGDg%40OFOGCTQIEL%3FIITUzBGdCA%60CItBYnFeB~Bq%40nCYlCI%60CJtBZ%7CEfApBj%40zAp%40t%40v%40tApBr%40l%40%60BlAh%40TtBn%40dCn%40l%40HH%3FxBb%40jFrAbAZ%60FlApJ%7CAzAHdB%40%60BM%60BUpAe%40bBOzADjAf%40nBVz%40%5DUqBBm%40Fc%40AEI%3Fk%40SEI%40Sh%40ABA_%40IKEFILEA%3FJUNEn%40LYGXDDDa%40MYLYRJDO%40EN%40JHJRBFH%40JNPBFABEE%40%3FFOb%40_BXe%40b%40c%40V%5D%3FGADHWpASnCMxBYr%40OE%40x%40G~%40Sv%40_%40%5EY%60%40On%40a%40jB%7D%40%5EWAG%3FBBC%3FEYOB%40AA%40%3FE%40DAC%40BACADBCA%40%40C%3F%40A%40DJDA%3FACRDFCENIFDE%40K%5E_%40tEaB~B%7DAxUeDlA_ANGT%5BFOAGBMJUXUNB%40PJJEFICXYVDHAQ%3F%5DNYAOB%7C%40SY%3FGDCHYLUTB%40KBAHHVj%40b%40%5C%60%40lAj%40rDfAxCp%40jAb%40b%40XlBhBvAv%40Sd%40wAP%7BDNeEZyDf%40kAYi%40_%40YMAEPNGID%40I%3FL%40BAACRJ%5CFRA~AX%5EECKA%40BCB%40%3FDC%3FB%3FABHEGHEADA%40AMLFIA%40LAI%3FB%3F%3FCM%3FEHBAUBLCl%40FFAx%40b%40I%60%40YXEN%5CNH%40%40AGAC%40XHBXB%40BAE%3FD%3FM%40GH%40%40JQHAGDDAA%40M%40JI%3FHA%3FB%3FI%40%40A%40AMH%40D%40MJG%3FBGDJBEFO%40TY%40DDAGAADA%40BA%3FAIJE%3FENBCG%40%40AADO%40NA%40AEABA%3FBRMAEFEC%3FA%40NBIED%3FM%3FLFMS%40ELBKFHEIIyAm%40AEJM%5CMHBD%3FIOFCBDI%3FSF%3F%40IEF%3FBD%40E%40DHACA%3FFB%3Fk%40OSCXAODBBG%3F%60%40%40GBD%40C%3FOCBBMEBFCA%3FIGDE%3F%40%3FB_%40C%5EJFJKs%40Q%5EZCGB%3FJD_%40CCCj%40%40OFECFAC%3FWDRIREULRE%40CP%3Fj%40HADQGEFNDFHAJUHGFJZV%40BQW%3FJE%40BM%3FH%3FG%3FTFOADIRLBTEB%40F%40%3FAKCEBBECPN%40HHGB%40CEIB%3FCGDHCE%40BEF%40G%40BACB%40F%40EA%3F%40CE%3FDAE%40FAG%3FB%3FCBDCE%3FF%40GCFD%3FAG%3FGED%40%40NAIFIDAG%3FBDLBA%40QABA%40%40EAABMGKM%5B%40MQABPEG%3FyAm%40%5Cm%40%7CAWMEi%40%40gANk%40DkE_C%7BBwAyLoBmBpAy%40d%40UDJBKDGKDAADC%3F%3FED%40EBBA%3FCB%40EA%40%40M%40RABSLLHBAA%40A%3FDCEBDIA%3F%40OMUK_%40%40%5BF%7BDd%40_%40PW%5E_%40DmA%5Ds%40Wg%40WgAs%40oA_AI%5DBc%40Fa%40Ig%40%7BAcCSe%40c%40S%7B%40Aw%40GFa%40%60%40g%40Rc%40%3F_%40Ei%40c%40C%7DBXsDK_CJy%40J_CHeC%3F%7D%40DeAA%7D%40Eo%40MRc%40AWPw%40AYOs%40a%40o%40SSe%40mCA_AMuAToDj%40InACA%3F%3FBAADHCVSHADLA%40DG%40%40IQM%3FGNGHSCKJVWPEHn%40C%3FEFHm%40CEEDEl%40E%40CDA_%40%40mB%5CYh%40E%60Bs%40%60%40_BDaBNeA%5EaBXsBTiAf%40LbA%5C~%40%5ClADlAOhASlE%3FxAW~Cy%40bAwEpAc%40v%40%40dAfAbAtBt%40tCV%7CBVb%40~%40c%40nAIh%40%7C%40HfBHnBBhBG~G%5D%60BM~DOzDSfQeBx%40YnBsAxBoAn%40a%40pBaAFAHDQ%5Ea%40%5E%5DNPXbA%60%40EBAGUQTA%3FE%40FEAV%5C%3FBPEDSnCoAbAk%40AD_%40IJ%40%40FCAJAV%40BES%3F%40CZEABg%40EJHIK%3FDDBEDN%3FM%3FH%3FEAA%40D%3FABAG%3FBR%3FS%40DCLDOCLBSUICB%40AD%40ACGD%40C%3F%40HIQHBK%3F%3FA%3F%40DC%3FB%40AEB%40%40J%3FGAFCG%40%40CE%3FFB%3FCI%3FB%3F%40F%40M%3FFBBIE%3FD%3FEBBAAD%40K%3F%40AHDECFBDEK%40BFEAFC%3FDAEKFFGHDCKA%40AA%40DHCMCFBEGAFACJFG%3FHAI%3FD%40CBBCBBEKDBM%40%...
```

Suggestions from Perplexity: The full error message you provided:

```
HttpException: HttpException: Invalid statusCode: 413, uri = https://api.mapbox.com/styles/v1/mapbox/dark-v11/static/path-12+fff-0.8(oxgq%40gkvpHd%40IeAPJFC%40DBC%40NHRC_...
```

indicates that your request to the Mapbox Static Images API was rejected because the request URI is too long or the payload is too large for the server to handle[1]. The HTTP status code 413 means "Payload Too Large," so the server is signaling that it cannot process the request because it exceeds its configured size limits.

**In this specific case:**
- The error is triggered when sending a very large or complex path parameter in the URL to Mapbox’s static map endpoint.
- The encoded path in your URI is extremely lengthy, likely exceeding Mapbox's limits for URL length or data size for a single static map request.

**How to resolve:**
- Simplify or reduce the number of points in the path you are sending to Mapbox.
- Consider splitting the request into smaller segments if possible.
- Check Mapbox’s documentation for limits on URL length or the number of coordinates allowed in a static map path.

**Summary:**  
Your request to Mapbox failed because the path data in your URL is too large, breaching the server’s limits for a single request[1]. Try reducing the complexity or size of the path parameter.

[1] https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/19754902/101271fe-c3ac-4583-8361-71041acc323a/paste.txt

### PR DESCRIPTION
**Pull request by mashazyu**
Closes #94

### Detailed Changes

*   add condition to make sure url length never exceets 7995
*   tests

### Testing
Tracks list and individual tracks view should work as before.

### Checklist before requesting a review

[X] I have performed a self-review of my code
[X] I have added or updated tests
[ ] I have added or updated relevant documentation

### Additional Information
- This is explanation from Perplexity on api limit - https://www.perplexity.ai/search/what-this-error-message-can-be-MaCyJ.5jR7m8iMhENj3avg
- Isar usage in tests https://stackoverflow.com/questions/74307526/running-unittests-with-isar-in-flutter

### CODE REVIEW

File: lib/models/track_data.dart [hunk 1]
```diff
@@ -68,17 +68,24 @@ class TrackData {
...
+        tolerance: tolerance,
+        highestQuality: false,
+      );
+      final simplifiedList =
+          simplifiedCoordinates.map((point) => [point.x, point.y]).toList();
+      polyline = encodePolyline(simplifiedList);
+      // Mapbox API URL lenght limit is 8192 bytes,
+      // other parts of URL are 197 bytes long
+      // which leaves us with 7995 bytes for the polyline
+    } while (polyline.length > 7950 && tolerance > 0.005);
```
Comment (mashazyu) [inline lib/models/track_data.dart:87]: **suggestion:** Just in case, I compare polyline length is slightly lower number.

**Review by felixerdy — APPROVED** [review]
LGTM
