### PR TITLE
Fix: ble connectivity 

### LINKED ISSUE #64: [Bug]: review bluetooth reconnection functionality
Track recorded by this bike might indicate that there are problems with connection to the box https://opensensemap.org/explore/68151ede2c7e450007c4e67e

- GPS data is stored consistently
- Temp data has breaks
- Some other sensors have less breaks in datapoints then Temp

## Expected Behavior

- Sensor data is pushed as consistently as GPS data

## Current Behavior

See above

## Steps to Reproduce

Maria should review her tracks, she might have seen this behavior

## Environment

*   App Build Number: 3.2.1

### PR DESCRIPTION
**Pull request by mashazyu**
Closes #64 
#45 

### Detailed Changes

*   When searching for ble device, after timeout, if no device found, error message is displayed
*   If phone looses connection to the box, it reconnects
*   I ran into situation when after connection/reconnection not all services are discovered. I addressed that issue as well
*   Refactor DeviceSelectionDialog, BleBloc, SensorBloc
*   Hide sensors, if no device connection

Open questions:
- I set minimum required services to be discovered on device to 7 based on the number of services I have on my Atrai test device. Would this number work also for Classic device?
- I ran into issue that, if connection to the box is re-established quickly, sensors data cannot be retrieved. Therefore I suggested the following logic
    - reconnect successfully
    - wait for 10 seconds
    - connect once again and start reading characteristics.
Does this make sense to you? Is there any delay defined in senseBox technical documentation? For example, how long does it take to load the box? I think using this info would be better than some random number.
- Could you please review english and german translations?
- Does your phone vibrate on disconnect? I verified that it should, but my phone doesn't. I suspect it must be some wierd settings I have, so could you please verify that from your end?

### Testing

Please break it.

### Checklist before requesting a review

[X] I have performed a self-review of my code
[ ] I have added or updated tests
[ ] I have added or updated relevant documentation

### CODE REVIEW

File: lib/blocs/ble_bloc.dart [hunk 1]
```diff
@@ -1,20 +1,35 @@
...
+import 'package:provider/provider.dart';
 import 'package:sensebox_bike/blocs/recording_bloc.dart';
 import 'package:sensebox_bike/services/custom_exceptions.dart';
-import 'package:vibration/vibration.dart'; // Import the RecordingBloc
+import 'package:vibration/vibration.dart';
+
+const reconnectionDelay = Duration(seconds: 5);
+const deviceConnectTimeout = Duration(seconds: 10);
+// Minimum number of services to consider a valid connection
+const minimumServices = 7;
```
Comment (felixerdy) [inline lib/blocs/ble_bloc.dart:16]: Using `7` did not work for me (app did not connect with device). Testing with `1` solved the issue
