### PR TITLE
Bug: app hangs on login screen

### LINKED ISSUE #10: Fix connection issue on iOS
Some users reported connection issues, especially on iOS

One user told me that connection is quite stable after connecting to the senseBox:bike, there are issues when starting to record a track. Maybe there is an issue with the database writing a lot of data. Maybe we should buffer data and write them to the db in packages

### LINKED ISSUE #16: Login screen: app hangs, when navigate login page
## Description
On the first app login, if navigate to the login page, app hangs and throws an error and app hangs

## Steps to reproduce
- Open app
- click login button
=> app hangs

## Additional information
This is [where](https://github.com/reedu-reengineering-education/sensebox-bike-flutter/blob/main/lib/blocs/opensensemap_bloc.dart) the error is thrown  
```
  Future<List> fetchSenseBoxes({int page = 0}) async {
    try {
      var myBoxes = await _service.getSenseBoxes(page: page);
      _senseBoxes[page] = myBoxes;
      notifyListeners();
      return myBoxes;
    } catch (e) {
      throw Exception('Failed to fetch senseBoxes');
    }
  }
```

### LINKED ISSUE #17: Battery drain
A user mentioned a high battery drain while using the app (connected to sensebox:bike and recording a track). After 30 min ride, the battery was almost empty. We should check why this is happening.

I am still waiting for more details, like smartphone model etc.

### PR DESCRIPTION
**Pull request by mashazyu**
Closes #16 
Closes #10 (?) 
Closes #17 (?) 

As we discussed previously, I took 2 approaches:
- reviewed code of OpenSenseMapService and OpenSenseMapBloc,
- looked for problems in DevTools and addressed most prominent ones.

### Detailed Changes

*   refactor OpenSenseMapBloc, OpenSenseMapService to improve readibility
*   add tests for OpenSenseMapService
*   refactor IsarService to use singleton pattern = prevent creation of multiple instances of a service
*   refactor navigation to prevent generation of multiple instances of widget
*   refactor LoginForm and RegisterForm and disable login and register button to prevent multiple login/registration event submission
*   LiveUploadService: limit number of reconnection attempts

### Testing
1. I can navigate to the login screen right after app starts, this is why I assume that #16 is fixed with this PR.
2. I walked a bit with a senseBox and compared functionality of current version of app with one in the Google PlayStore. 
- I noticed that Google PlayStore version stopped recording data for a bit.
- After a couple of tests with current version I didn't notice any disconnects, therefore I assume that this PR closes also #10 .
3. LiveUploadService: I verified that if i 
- start track recording,
- disable Internet connection on my phone,
- enable it back in 6 minutes
=> data flow to openSenseMap dashboard restores. 
4. I can login to the existing and register new account. Also i verified that I get error messages, when I use incorrect data (including validation).

Open questions 
- if refreshing auth- and refresh tokens makes sense to you.

### Checklist before requesting a review

[X] I have performed a self-review of my code
[ ] I have added or updated relevant documentation

### CODE REVIEW

File: lib/blocs/opensensemap_bloc.dart [hunk 1]
```diff
@@ -9,48 +9,75 @@ import 'package:shared_preferences/shared_preferences.dart'; // Add for StreamCo
...
-
   SenseBox? get selectedSenseBox => _selectedSenseBox;
-
   bool get isAuthenticated => _isAuthenticated;
   List<dynamic> get senseBoxes => _senseBoxes.values.expand((e) => e).toList();
 
   OpenSenseMapBloc() {
-    _service.refreshToken().then(
-        (_) async => {_isAuthenticated = true, await loadSelectedSenseBox()});
+    _initializeAuth();
```
Comment (mashazyu) [inline lib/blocs/opensensemap_bloc.dart:25]: **suggestion (non-blocking):**  This was done to allow async call in constructor.

File: lib/services/isar_service.dart [hunk 2]
```diff
@@ -11,6 +11,11 @@ import 'package:sensebox_bike/services/isar_service/sensor_service.dart';
 import 'package:sensebox_bike/services/isar_service/track_service.dart';
 
 class IsarService {
+  // Use Singleton pattern to avoid creation of multiple instances
```
Comment (mashazyu) [inline lib/services/isar_service.dart:14]: **suggestion (non-blocking):** This part is turning IsarService to singleton to avoid creation of multiple instances.

File: lib/ui/widgets/common/button_with_loader.dart [hunk 3]
```diff
@@ -0,0 +1,39 @@
+import 'package:flutter/material.dart';
```
Comment (mashazyu) [inline lib/ui/widgets/common/button_with_loader.dart:1]: **suggestion (non-blocking):** Just moving some code to separate components. More can be done, but I decided to stop here :)

File: lib/services/live_upload_service.dart [hunk 4]
```diff
@@ -66,6 +94,21 @@ class LiveUploadService {
     });
   }
 
+  Future<void> uploadDataWithRetry(Map<String, dynamic> data) async {
```
Comment (mashazyu) [inline lib/services/live_upload_service.dart:97]: **suggestion (non-blocking):** Basically I moved handling on 429 error from OpenSenseMapService to the LiveUploadService.

File: lib/services/opensensemap_service.dart [hunk 5]
```diff
@@ -150,224 +164,50 @@ class OpenSenseMapService {
...
 
-    final response = await http.post(
-      Uri.parse('$_baseUrl/boxes/$senseBoxId/data'),
-      body: jsonEncode(data),
-      headers: {
-        'Authorization': 'Bearer $accessToken',
-        'Content-Type': 'application/json',
-      },
-    );
+    try {
```
Comment (mashazyu) [inline lib/services/opensensemap_service.dart:174]: **suggestion (non-blocking):** Here I am forcing timeout of POST request because during testing I encountered the situation, when app hanged because I never received response to the POST request and as far as I understand by default requests never time out.

**Comment by mashazyu** [comment]
@felixerdy ,

Thank you very much for the review!

For the documentation purposes:
- Felix found that data upload never restarted after 429 error (only 6 data uploads per minuter are allowed by the backend).
- Felix confirmed that retry logic that I had in mind was acceptable.

I addressed this issue.

Testing done from my side:
- I see that data upload restarts after 429 error. I also see that sometimes it looks like data upload is restarted too early (?) and after 1 upload I get reply 429 with retry-after 1 second. This can happen a couple of times in a row. I don't want to add randomly a couple of seconds to retry-after value from headers to address this. But, if you feel that it would be a good workaround for now, I'm happy to do so.
- I verified that in case of connectivity issues data transfer is restarted after timeout.
- If max timeout is reached, data transfer never restarts automatically.

**Comment by felixerdy** [comment]
@mashazyu Thank you for the changes. Data upload is now working as expected. I just discovered a minor UX bug:

**Situation**
When opening the app (after closing it completely), it always looks like I have to login again. After clicking on the login button, the drawer opens and loads the senseBox devices from my account. Thus, I was already logged in. Dismissing the drawer shows the icon to select a senseBox device (linking icon), even though I selected a device last time before closing the app

**Expected**
When opening the app (after closing it completely), the app should check if I'm still logged in and remember the selected senseBox device 

**Screenshots**
| After opening app | After clicking login icon | After dismissing drawer (without selecting device) |
| ------- | ------------ | ------- |
| IMG_6045 | IMG_6046 | IMG_6047 |

**Comment by mashazyu** [comment]
> @mashazyu Thank you for the changes. Data upload is now working as expected. I just discovered a minor UX bug:
> 
> **Situation** When opening the app (after closing it completely), it always looks like I have to login again. After clicking on the login button, the drawer opens and loads the senseBox devices from my account. Thus, I was already logged in. Dismissing the drawer shows the icon to select a senseBox device (linking icon), even though I selected a device last time before closing the app
> 
> **Expected** When opening the app (after closing it completely), the app should check if I'm still logged in and remember the selected senseBox device
> 
> **Screenshots*)
> 

Hello @felixerdy ,

Thank you very much! The issue should be fixed now :)
